#!/bin/bash
#
# Benchmark for C code.

echo "Benching C"
echo "---------------"

TIMEFORMAT=%R

t1=$((time ./prime > /dev/null) 2>&1)
echo "Trial 1: ${t1}s"
t2=$((time ./prime > /dev/null) 2>&1)
echo "Trial 2: ${t2}s"
t3=$((time ./prime > /dev/null) 2>&1)
echo "Trial 3: ${t3}s"

avg=$(echo "scale=3;(${t1}+${t2}+${t3})/3" | bc)
printf "\nAverage: 0%ss\n" "${avg}"
